### ISSUE TITLE
`length error running .nlp.findDates

### ISSUE THREAD

**Issue by tepu** [KxSystems/nlp#7]
.nlp.findDates throws `length errors on the following inputs
"5.24.01"
"December 18-January 2"
"memo of 10-5 1 page.doc"

Running it on the Enron emails, it is throwing `length on ~8% of the emails

**Comment by fionncarr** [comment]
Hi tepu,

The error was occurring as there wasn't picking up the format of the date correctly. This bug should be fixed now if you clone this repository again. 
 
``` 
q).nlp.findDates"5.24.01"
2024.05.01 2024.05.31 "5.24" 0 4
q).nlp.findDates"December 18-January 2"
2018.12.01 2018.12.31 "December 18" 0 11
q).nlp.findDates"memo of 10-5 1 page.doc"
2010.05.01 2010.05.01 "10-5 1" 8 14
``` 
  Let me know if you have any issues,

Thanks,

Fionnuala

**Comment by awilson-kx** [comment]
Closing issue
